# Chocolatey
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# install applications
choco install javaruntime-preventasktoolbar
choco install nodejs-lts
choco install fiddler4
choco install tortoisesvn
choco install micro
choco install 7zip.install
choco install googlechrome
choco install adobereader
choco install jdk8
choco install firefox
choco install vlc
choco install git.install
choco install sysinternals
choco install filezilla
choco install curl
choco install procexp
choco install wget
choco install paint.net
choco install dropbox
choco install itunes
choco install windirstat
choco install visualstudiocode
choco install poshgit
choco install sourcetree
choco install cmder
choco install phantomjs
choco install docker-for-windows
choco install spotify
choco install jq
choco install yarn
choco install lastpass
choco install dotpeek
choco install slack
choco install psake
choco install linqpad
choco install p4v

#choco install beyondcompare
#choco install resharper
